// <auto-generated />
using System;
using Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Entities.Migrations
{
    [DbContext(typeof(MySQLiteContext))]
    [Migration("20260104060646_InitialSecurityV2")]
    partial class InitialSecurityV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Api.Entities.Cobrador", b =>
                {
                    b.Property<int>("Id_cobrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_cobrador");

                    b.ToTable("Cobrador");
                });

            modelBuilder.Entity("Api.Entities.CobradorLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_cobrador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_cobrador");

                    b.ToTable("CobradorLog");
                });

            modelBuilder.Entity("Api.Entities.Concepto", b =>
                {
                    b.Property<int>("Id_concepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_alta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_concepto");

                    b.ToTable("Concepto");
                });

            modelBuilder.Entity("Api.Entities.ConceptoLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_concepto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_concepto");

                    b.ToTable("ConceptoLog");
                });

            modelBuilder.Entity("Api.Entities.Folio", b =>
                {
                    b.Property<int>("Id_folio_serie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio_vigente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Id_gremio")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Siguiente_folio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_folio_serie");

                    b.HasIndex("Id_gremio");

                    b.ToTable("Folio");
                });

            modelBuilder.Entity("Api.Entities.Gremio", b =>
                {
                    b.Property<int>("Id_gremio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_alta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_lider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_gremio");

                    b.HasIndex("Id_lider");

                    b.ToTable("Gremio");
                });

            modelBuilder.Entity("Api.Entities.GremioLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_gremio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_lider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_gremio");

                    b.ToTable("GremioLog");
                });

            modelBuilder.Entity("Api.Entities.Lider", b =>
                {
                    b.Property<int>("Id_lider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_alta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_lider");

                    b.ToTable("Lider");
                });

            modelBuilder.Entity("Api.Entities.LiderLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_lider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_lider");

                    b.ToTable("LiderLog");
                });

            modelBuilder.Entity("Api.Entities.MatriculaContador", b =>
                {
                    b.Property<string>("Tipo_vendedor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Siguiente_numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Tipo_vendedor", "Anio");

                    b.ToTable("MatriculaContador");
                });

            modelBuilder.Entity("Api.Entities.Padron", b =>
                {
                    b.Property<int>("Id_padron")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_alta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_gremio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula_anterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_vendedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_padron");

                    b.HasIndex("Id_gremio");

                    b.ToTable("Padron");
                });

            modelBuilder.Entity("Api.Entities.PadronLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_padron")
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_gremio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula_anterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_vendedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_padron");

                    b.ToTable("PadronLog");
                });

            modelBuilder.Entity("Api.Entities.Recaudacion", b =>
                {
                    b.Property<int>("Id_recaudacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_cobro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio_Recibo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_concepto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_padron")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_recaudacion");

                    b.HasIndex("Id");

                    b.HasIndex("Id_concepto");

                    b.HasIndex("Id_padron");

                    b.ToTable("Recaudacion");
                });

            modelBuilder.Entity("Api.Entities.Tarifa", b =>
                {
                    b.Property<int>("Id_tarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_alta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_concepto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_gremio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_tarifa");

                    b.HasIndex("Id_concepto");

                    b.HasIndex("Id_gremio");

                    b.ToTable("Tarifa");
                });

            modelBuilder.Entity("Api.Entities.TarifaLog", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_tarifa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_concepto")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Id_gremio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_movimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_movimiento", "Id_tarifa");

                    b.ToTable("TarifaLog");
                });

            modelBuilder.Entity("Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_materno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("A_paterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPasswordTemporal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_alta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_modificacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_alta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario_modificacion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Folio", b =>
                {
                    b.HasOne("Api.Entities.Gremio", "Gremio")
                        .WithMany()
                        .HasForeignKey("Id_gremio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gremio");
                });

            modelBuilder.Entity("Api.Entities.Gremio", b =>
                {
                    b.HasOne("Api.Entities.Lider", "Lider")
                        .WithMany()
                        .HasForeignKey("Id_lider")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("Api.Entities.Padron", b =>
                {
                    b.HasOne("Api.Entities.Gremio", "Gremio")
                        .WithMany()
                        .HasForeignKey("Id_gremio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gremio");
                });

            modelBuilder.Entity("Api.Entities.Recaudacion", b =>
                {
                    b.HasOne("Api.Entities.Usuario", "Cobrador")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Concepto", "Concepto")
                        .WithMany()
                        .HasForeignKey("Id_concepto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Padron", "Padron")
                        .WithMany()
                        .HasForeignKey("Id_padron")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobrador");

                    b.Navigation("Concepto");

                    b.Navigation("Padron");
                });

            modelBuilder.Entity("Api.Entities.Tarifa", b =>
                {
                    b.HasOne("Api.Entities.Concepto", "Concepto")
                        .WithMany()
                        .HasForeignKey("Id_concepto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Gremio", "Gremio")
                        .WithMany()
                        .HasForeignKey("Id_gremio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concepto");

                    b.Navigation("Gremio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Api.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
