# For more info on HTTP files go to https://aka.ms/vs/httpfile
# Configuración de variables
@HostAddress = https://localhost:7011

### Solicitud de lotes
POST {{HostAddress}}/api/Folio/SolicitarLote?id=4
Accept: application/json