# For more info on HTTP files go to https://aka.ms/vs/httpfile
@HostAddress = https://localhost:7011

POST {{HostAddress}}/api/recaudacion/Create
Content-Type: application/json

{
  "idPadron": 2,
  "idGremio": 1,
  "idConcepto": 3,
  "idCobrador": 1,  
  "latitud": 18.4437236,
  "longitud": -96.3657014,
  "monto": 90.0
}